### ISSUE TITLE
在 library 中删除不必要且会带来麻烦的 <application/> 声明和 string 资源文件

### ISSUE THREAD

**Issue by drakeet** [fython/AlipayZeroSdk#1]
https://github.com/fython/AlipayZeroSdk/blob/0f6981edbf3d4a9cbe0cf3f88c55a1be8a5105d7/library/src/main/AndroidManifest.xml#L4-L4

https://github.com/fython/AlipayZeroSdk/blob/0f6981edbf3d4a9cbe0cf3f88c55a1be8a5105d7/library/src/main/res/values/strings.xml#L2-L2

以上两行代码都是不必要且会带来使用者代码冲突的麻烦，都是应该删除的。

**Comment by fython** [comment]
了解，已提交修复： f3989a43966b3fb53f22b7cb2e5d5aa43f91c768
