### ISSUE TITLE
支付宝是否不推荐这种推广方式 收到了一个警告

### ISSUE THREAD

**Issue by bestbai** [fython/AlipayZeroSdk#10]
付款链接是正常的，这说的这问题是链接到了赏金推广上。
请看图，以前能用的链接，近期开始弹出警告提示：该红包推广可能不是官方认可的推广方式！后续如果您在参与本活动时被恶意推广，可在领取结果页进行举报。
![11538102260_ pic_hd](https://user-images.githubusercontent.com/25720860/46185135-43b54100-c2c8-11e8-896e-bb4766a5f7b9.jpg)

**Comment by fython** [comment]
这个库的教程没有提及过如何使用它来调用红包码，请问是在仅用于开始转账时弹出的警告吗？

**Comment by bestbai** [comment]
收款码的解析内容为HTTPS://QR.ALIPAY.COM/22位大写字符
红包码的解析内容为https://qr.alipay.com/23位小写字符
两种码的结构基本相同，只是有大小写区别，都是调用AlipayZeroSdk的扫码接口，传入红包码内容时会有警告，而以前是完全正常的。

**Comment by fython** [comment]
支付宝推广商户红包码本来是线下形式，而直接在手机内点击链接会被认为是刷红包行为。本库的目的也不是为了在手机上推广红包码，不推荐用来打开红包码。

暂时关闭这条 Issue，但仍欢迎继续交流支付宝的使用问题。
