### ISSUE TITLE
关于二维码转账的一些问题

### ISSUE THREAD

**Issue by yuqirong** [fython/AlipayZeroSdk#5]
打开转账窗口
旧版支付宝二维码方法，需要使用 https://fama.alipay.com/qrcode/index.htm 网站生成的二维码
这个方法最好，但在 2016 年 8 月发现新用户可能无法使用

你好，在 startAlipayClient 方法中有相关的注释，其中 “2016 年 8 月发现新用户可能无法使用” 有什么依据吗。有没有解决的方法？

**Comment by fython** [comment]
那个网站有一段时间存在问题，无法正确地打开生成二维码的页面，而现在已经有了更方便的网站（支付宝官方）去生成二维码。

**Comment by feer921** [comment]
// 支付宝包名
	private static final String ALIPAY_PACKAGE_NAME = "com.eg.android.AlipayGphone";

这是支付宝安卓客户端的包名？

**Comment by yuqirong** [comment]
@feer921 是的
