### ISSUE TITLE
能否拿到支付的回调呢？

### ISSUE THREAD

**Issue by narakai** [fython/AlipayZeroSdk#7]
谢谢开发了这个库，麻烦问下能否拿到支付宝支付完成的回调呢？

**Comment by fython** [comment]
这个库没法获得回调，仅仅是模拟完成扫描二维码后弹出转账窗口。

如果没有商户帐号，又希望能够检查订单是否合法，可以尝试一下：[thundernet8/AlipayOrdersSupervisor](https://github.com/thundernet8/AlipayOrdersSupervisor)

**Comment by narakai** [comment]
谢谢回复
