### ISSUE TITLE
地址打不开了

### ISSUE THREAD

**Issue by hp-xiaomage** [fython/AlipayZeroSdk#8]
https://fama.alipay.com/qrcode/qrcodelist.htm?qrCodeType=P

**Comment by captain-miao** [comment]
支付宝客户端-首页-收钱-微信扫-就可以拿到「 个人收款的二维码参数」

**Comment by fython** [comment]
现在直接使用支付宝客户端的收款二维码即可。我改一下 README.md 吧。
